//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecisionEngineering.I18N {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_HK() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrecisionEngineering.I18N.zh-HK", typeof(zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        internal static string option_changu {
            get {
                return ResourceManager.GetString("option.changu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        internal static string option_da {
            get {
                return ResourceManager.GetString("option.da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公制 的本地化字符串。
        /// </summary>
        internal static string option_gongzhi {
            get {
                return ResourceManager.GetString("option.gongzhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計量單位 的本地化字符串。
        /// </summary>
        internal static string option_jiliangdanwei {
            get {
                return ResourceManager.GetString("option.jiliangdanwei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特大 的本地化字符串。
        /// </summary>
        internal static string option_teda {
            get {
                return ResourceManager.GetString("option.teda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英制 的本地化字符串。
        /// </summary>
        internal static string option_yingzhi {
            get {
                return ResourceManager.GetString("option.yingzhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 語言（Language） 的本地化字符串。
        /// </summary>
        internal static string option_yuyan {
            get {
                return ResourceManager.GetString("option.yuyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字體大小 的本地化字符串。
        /// </summary>
        internal static string option_zitidaxiao {
            get {
                return ResourceManager.GetString("option.zitidaxiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高: {0} 的本地化字符串。
        /// </summary>
        internal static string unit_gao {
            get {
                return ResourceManager.GetString("unit.gao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高程: {0} 的本地化字符串。
        /// </summary>
        internal static string unit_gaocheng {
            get {
                return ResourceManager.GetString("unit.gaocheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}格 的本地化字符串。
        /// </summary>
        internal static string unit_ge {
            get {
                return ResourceManager.GetString("unit.ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}格 ({1:#}米) 的本地化字符串。
        /// </summary>
        internal static string unit_ge_mi {
            get {
                return ResourceManager.GetString("unit.ge_mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}碼 的本地化字符串。
        /// </summary>
        internal static string unit_ma {
            get {
                return ResourceManager.GetString("unit.ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}碼  {1:#}英尺 的本地化字符串。
        /// </summary>
        internal static string unit_ma_yinchi {
            get {
                return ResourceManager.GetString("unit.ma_yinchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}米 的本地化字符串。
        /// </summary>
        internal static string unit_mi {
            get {
                return ResourceManager.GetString("unit.mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#}英尺 的本地化字符串。
        /// </summary>
        internal static string unit_yinchi {
            get {
                return ResourceManager.GetString("unit.yinchi", resourceCulture);
            }
        }
    }
}
